[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["resend"]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Ensure sitemap.xml and robots.txt are not redirected to index.html
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  
[build.environment]
  NODE_VERSION = "18" 